chore: refresh env every private repo update

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -20,21 +20,11 @@ gw_dir=/massbit/massbitroute/app/src/sites/services/gateway
 
 cmd_server=$SITE_ROOT/cmd_server
 
-_env() {
-	if [ -z "$MBR_ENV" ]; then exit 1; fi
-	export ENV_BRANCH=${ENV_BRANCH:-$MBR_ENV}
-	_git_clone $GIT_PRIVATE_READ_URL/massbitroute/env.git $SITE_ROOT/env $ENV_BRANCH
-	if [ -f "$SITE_ROOT/env/env.sh" ]; then
-		source $SITE_ROOT/env/env.sh
-	fi
-	if [ -f "$SITE_ROOT/env/env.lua" ]; then
-		cp $SITE_ROOT/env/env.lua $SITE_ROOT/src/
-	fi
-
-}
-
 _init() {
-	if [ -z "$MBR_ENV" ]; then exit 1; fi
+	if [ -z "$MBR_ENV" ]; then
+		echo "MBR_ENV missing"
+		exit 1
+	fi
 	# if [ -e "$SITE_ROOT/cmd_server" ]; then bash $SITE_ROOT/cmd_server _env; fi
 
 	# if [ -f "$SITE_ROOT/.env_raw" ]; then source $SITE_ROOT/.env_raw; fi
@@ -124,7 +114,7 @@ _install_repos() {
 
 	for _pathgit in $REPOS; do
 		# _repo
-		_env
+		# _env
 		_path=$(echo $_pathgit | cut -d'|' -f1)
 		_url=$(echo $_pathgit | cut -d'|' -f2)
 		_branch=$(echo $_pathgit | cut -d'|' -f3)
@@ -465,6 +455,10 @@ _update_listid() {
 	awk -v domain="$DOMAIN" '{print $5,$1".gw.mbr."domain}' $info_dir/listid >>$portal_dir/public/deploy/info/hosts
 }
 _update_repos() {
+	if [ -z "$MBR_ENV" ]; then
+		echo "MBR_ENV missing"
+		exit 1
+	fi
 	if [ -z "$GIT_PRIVATE_READ_URL" ]; then
 		echo "Need GIT_PRIVATE_READ_URL"
 		exit 1
