Release (#213)
* chore: sleep and check file exists #198

* bugfix: check env lua existed #5

* feat: add debug info for node register

* chore: sleep and check file exists #198

* chore: select keiko is default env

* bugfix: branch conflict resolve

* bugfix: check env lua existed #5

* bugfix: branch conflict resolve

* bugfix: branch conflict resolve

* fix: supervisor option

* fix: clean up flow

* fix: cleanup update_repos

* fix: cleanup update_repos

* chore: add _env to update env

* chore: refresh env every private repo update

* fix: add _env function

* fix: check env dir existence

* fix: load _env in init func

* chore: enable _update flow

* chore: enable _update flow

* chore: enable _update flow

* chore: update update_repos, install_repos

* chore: add commit_repos

* chore: add commit_repos

* fix: wrong path

* fix: wrong path

* fix: wrong path var name

* fix: wrong status var

* fix: wrong status var

* fix: add load _env

* chore: seperate private with runtime repos

* fix: clone only dir without .git dir

* fix: do not check var GIT_PRIVATE_READ_URL in install repos

* fix: add runtime_repos in update repos phase

* fix: change format default for env whitelist_partners

* chore: change allow ip for internal api via env API_INTERNAL_IP_ALLOW

* fix: update HOME & remove check  GIT_PRIVATE_READ_URL in install phase

* fix: update HOME & remove check  GIT_PRIVATE_READ_URL in install phase

* fix: do not call _env on _repo

* fix: do not call _env on _repo

* fix: do not call _env on _repo

* fix: clean up GIT_PUBLIC_URL

* fix: clean up GIT_PUBLIC_URL

* fix: clean up GIT_PUBLIC_URL

* fix: clean up GIT_PUBLIC_URL

* chore: add API_DOMAIN_SSL env

* chore: replace exit by return

* chore: add _update

* fix: update _reload

* fix: add define DOMAIN or auto extract from PORTAL_URL

* chore: using GIT_PRIVATE_BRANCH as private branch for all private repo

* chore: turn autostart on (#212)

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -20,53 +20,75 @@ gw_dir=/massbit/massbitroute/app/src/sites/services/gateway
 
 cmd_server=$SITE_ROOT/cmd_server
 
+_reload() {
+	$cmd_server status | grep worker- | awk '{print $1}' | while read f; do
+		$cmd_server restart $f
+	done
+	$SITE_ROOT/cmd_server _update
+	$SITE_ROOT/cmd_server update
+	$SITE_ROOT/cmd_server start all
+}
 _repo() {
-	if [ -e "$SITE_ROOT/cmd_server" ]; then bash $SITE_ROOT/cmd_server _env; fi
 
-	if [ -f "$SITE_ROOT/.env_raw" ]; then source $SITE_ROOT/.env_raw; fi
-	export MBR_ENV=${MBR_ENV:-keiko}
-	# export BRANCH=${BRANCH:-$MBR_ENV}
-	# export MBRAPP_BRANCH=${MBRAPP_BRANCH:-$MBR_ENV}
-	export ASDF_BRANCH=${ASDF_BRANCH:-$MBR_ENV}
-	export GBC_BRANCH=${GBC_BRANCH:-$MBR_ENV}
-	export SSL_BRANCH=${SSL_BRANCH:-$MBR_ENV}
-	export GWMAN_BRANCH=${GWMAN_BRANCH:-$MBR_ENV}
-	export GWMANDEPLOY_BRANCH=${GWMANDEPLOY_BRANCH:-$MBR_ENV}
-	export NODE_BRANCH=${NODE_BRANCH:-$MBR_ENV}
-	export GATEWAY_BRANCH=${GATEWAY_BRANCH:-$MBR_ENV}
-	export STAT_BRANCH=${STAT_BRANCH:-$MBR_ENV}
-	export STATDEPLOY_BRANCH=${STATDEPLOY_BRANCH:-$MBR_ENV}
-	export MONITOR_BRANCH=${MONITOR_BRANCH:-$MBR_ENV}
-	export API_BRANCH=${API_BRANCH:-$MBR_ENV}
-	export APIDEPLOY_BRANCH=${APIDEPLOY_BRANCH:-$MBR_ENV}
-	export SESSION_BRANCH=${SESSION_BRANCH:-$MBR_ENV}
-	export GIT_BRANCH=${GIT_BRANCH:-$MBR_ENV}
-	export MKAGENT_BRANCH=${MKAGENT_BRANCH:-$MBR_ENV}
-	export MONITOR_BRANCH=${MONITOR_BRANCH:-$MBR_ENV}
-	export SESSION_BRANCH=${SESSION_BRANCH:-$MBR_ENV}
-	# $service_dir/api|$GIT_PUBLIC_URL/massbitprotocol/massbitroute.git|$API_BRANCH \
+	if [ -z "$MBR_ENV" ]; then
+		echo "MBR_ENV missing"
+		exit 1
+	fi
+	if [ -z "$GIT_PUBLIC_URL" ]; then
+		echo "GIT_PUBLIC_URL missing"
+		exit 1
+	fi
 	REPOS="\
-$SITE_ROOT/env|$GIT_PRIVATE_READ_URL/massbitroute/env.git|$MBR_ENV \
- $mbr_root/gbc|https://github.com/massbitprotocol/massbitroute_gbc|$GBC_BRANCH \
-/etc/letsencrypt|$GIT_PRIVATE_READ_URL/massbitroute/ssl.git|$SSL_BRANCH \
- $mbr_root/gbc/bin/.asdf|https://github.com/massbitprotocol/massbitroute_asdf|$ASDF_BRANCH \
   $service_dir/gwman|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_gwman.git|$GWMAN_BRANCH \
-  $service_dir/gwman/data|http://$GIT_GWMANDEPLOY_WRITE@$GIT_PRIVATE_DOMAIN/massbitroute/gwmandeploy.git|$GWMANDEPLOY_BRANCH \
-  $service_dir/api/public/deploy|http://$GIT_APIDEPLOY_WRITE@$GIT_PRIVATE_DOMAIN/massbitroute/apideploy.git|$APIDEPLOY_BRANCH \
-  $service_dir/mkagent|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_mkagent.git|$MKAGENT_BRANCH \
   $service_dir/node|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_node.git|$NODE_BRANCH \
   $service_dir/gateway|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_gateway.git|$GATEWAY_BRANCH \
 "
-	# $service_dir/stat|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_stat.git|$STAT_BRANCH \
-	# $service_dir/stat/etc/conf|http://$GIT_STATDEPLOY_WRITE@$GIT_PRIVATE_DOMAIN/massbitroute/statdeploy.git|$STATDEPLOY_BRANCH \
 
 }
-_repo
 
-#  $service_dir/api/public/mbr-app-prod|$GIT_PUBLIC_URL/massbitprotocol/mbr-app.git|$MBRAPP_BRANCH \
-#  $service_dir/monitor|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_monitor.git|$MONITOR_BRANCH \
-#  $service_dir/session|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_session.git|$SESSION_BRANCH \
-# _repo
+_repo_private() {
+	if [ -z "$MBR_ENV" ]; then
+		echo "MBR_ENV missing"
+		exit 1
+	fi
+	if [ -z "$GIT_PRIVATE_READ_URL" ]; then
+		echo "GIT_PRIVATE_READ_URL missing"
+		exit 1
+	fi
+	if [ -z "$GIT_PRIVATE_BRANCH" ]; then
+		echo "GIT_PRIVATE_BRANCH missing"
+		exit 1
+	fi
+
+	export MKAGENT_BRANCH=${MKAGENT_BRANCH:-$MBR_ENV}
+
+
+	export GBC_BRANCH=${GBC_BRANCH:-$MBR_ENV}
+	export ASDF_BRANCH=${ASDF_BRANCH:-$MBR_ENV}
+	export GWMAN_BRANCH=${GWMAN_BRANCH:-$MBR_ENV}
+
+	export ENV_BRANCH=${ENV_BRANCH:-$GIT_PRIVATE_BRANCH}
+	export SSL_BRANCH=${SSL_BRANCH:-$GIT_PRIVATE_BRANCH}
+	export GWMANDEPLOY_BRANCH=${GWMANDEPLOY_BRANCH:-$GIT_PRIVATE_BRANCH}
+	export APIDEPLOY_BRANCH=${APIDEPLOY_BRANCH:-$GIT_PRIVATE_BRANCH}
+
+	export NODE_BRANCH=${NODE_BRANCH:-$MBR_ENV}
+	export GATEWAY_BRANCH=${GATEWAY_BRANCH:-$MBR_ENV}
+	export API_BRANCH=${API_BRANCH:-$MBR_ENV}
+
+
+	_env
+
+	REPOS_RUNTIME="\
+  $service_dir/gwman/data|http://$GIT_GWMANDEPLOY_WRITE@$GIT_PRIVATE_DOMAIN/massbitroute/gwmandeploy.git|$GWMANDEPLOY_BRANCH \
+  $service_dir/api/public/deploy|http://$GIT_APIDEPLOY_WRITE@$GIT_PRIVATE_DOMAIN/massbitroute/apideploy.git|$APIDEPLOY_BRANCH \
+"
+	REPOS_PRIVATE="\
+$SITE_ROOT/env|$GIT_PRIVATE_READ_URL/massbitroute/env.git|$ENV_BRANCH \
+/etc/letsencrypt|$GIT_PRIVATE_READ_URL/massbitroute/ssl.git|$SSL_BRANCH \
+"
+
+}
 
 # _tune_os() {
 # 	#dns
@@ -82,64 +104,9 @@ _repo
 _prepare() {
 	echo "Prepare"
 	mkdir -p $SITE_ROOT/logs/nginx $SITE_ROOT/db $SITE_ROOT/tmp $SITE_ROOT/db
-
-	# rm -rf $SITE_ROOT/tmp/*
-	# if [ ! -f "/usr/bin/parallel" ]; then
-	# 	apt update
-	# 	apt install -y parallel
-	# fi
-
 	if [ ! -f "$SITE_ROOT/data/geoip/GeoIP2-City.mmdb" ]; then
-		# apt update
-		# apt-get install -y xz-utils
 		tar -xvJf $SITE_ROOT/data/geoip/GeoIP2-City.mmdb.tar.xz -C $SITE_ROOT/data/geoip
 	fi
-	# if [ -n "$DOMAIN" ]; then
-	# 	bash $SITE_ROOT/scripts/mbr_app.sh _build_prod $MBRAPP_BRANCH
-	# fi
-
-}
-
-_install_repos() {
-	_git_config
-
-	for _pathgit in $REPOS; do
-		_repo
-		_path=$(echo $_pathgit | cut -d'|' -f1)
-		_url=$(echo $_pathgit | cut -d'|' -f2)
-		_branch=$(echo $_pathgit | cut -d'|' -f3)
-		_git_clone $_url $_path $_branch
-	done
-}
-_init() {
-	if [ -z "$GIT_PRIVATE_READ_URL" ]; then
-		echo "Need GIT_PRIVATE_READ_URL"
-		exit 1
-	fi
-	# if [ ! -f "$SITE_ROOT/.env" ]; then
-	cat <<EOF >$SITE_ROOT/.env
-export GIT_PUBLIC_URL="https://github.com"
-export MBR_ENV=$MBR_ENV
-EOF
-	# fi
-
-	source $SITE_ROOT/.env
-
-	_repo
-	_git_clone $GIT_PRIVATE_READ_URL/massbitroute/env.git $SITE_ROOT/env $MBR_ENV
-	_git_clone $GIT_PUBLIC_URL/massbitprotocol/massbitroute_gbc.git /massbit/massbitroute/app/gbc
-
-	_repo
-	# if [ -e "$SITE_ROOT/cmd_server" ]; then bash $SITE_ROOT/cmd_server _env; fi
-	# if [ -f "$SITE_ROOT/.env_raw" ]; then source $SITE_ROOT/.env_raw; fi
-	# _git_clone $GIT_PUBLIC_URL/massbitprotocol/mbr-app.git $SITE_ROOT/public/mbr-app-prod $MBRAPP_BRANCH
-
-	# bash $SITE_ROOT/cmd_server _env
-	# source $SITE_ROOT/.env_raw
-	# _repo
-	# cat $SITE_ROOT/.env_raw
-	# source $SITE_ROOT/.env_raw
-
 }
 
 _supervisor() {
@@ -178,7 +145,6 @@ _install_test() {
 }
 
 _install_one() {
-	_init
 	_prepare
 	_install_repos
 }
@@ -216,203 +182,15 @@ EOF
 	cat $_conf >>http.d/${_id}.conf
 	# cat http.d/${_id}.conf
 
-	./cmd_server _updateconf
-	./cmd_server nginx -t
+	$cmd_server _updateconf
+	$cmd_server nginx -t
 	st=$?
-	# ./cmd_server nginx -T
 	rm -rf $_dir
 	return $st
 
 }
 
-_git_cmd_commit() {
-	_cdir=$1
-	_git="git -C $_cdir"
-	shift
-	if [ $# -gt 0 ]; then
-		_time=$(date -u)
-		_git_config $_cdir
-		for _fdir in $@; do
-			$_git add $_fdir
-		done
-		mid=$(cat /etc/machine-id)
-		ip=$(curl ipv4.icanhazip.com)
-		$_git pull
-		$_git commit -m "${ip}: ${mid}: ${HOSTNAME}: $_fdir at $_time"
-		$_git push
-		# commit_id=$($_git rev-parse origin/$($_git rev-parse --abbrev-ref HEAD))
-		# mkdir -p $SITE_ROOT/public/deploy/version
-		# repo_name=$(basename $($_git remote get-url origin) .git)
-		# echo $commit_id >$SITE_ROOT/public/deploy/version/${repo_name}.version
-		# 		mkdir -p $SITE_ROOT/public/deploy/version/${repo_name}
-		# 		cat >$SITE_ROOT/public/deploy/version/${repo_name}/${commit_id}.sh <<EOF
-		# #!/bin/bash
-		# echo "Update for $commit_id"
-		# EOF
-	fi
-}
 
-_git_cmd() {
-	cmd=$1
-	shift
-	list_push="apideploy gwmandeploy statdeploy"
-	list_pull="api gwman stat $list_push"
-	list_all="$list_pull gateway node mkagent"
-	if [ -z "$cmd" ]; then cmd=push; fi
-
-	list=""
-	case "$cmd" in
-	all)
-		list="$list_all"
-		cmd="pull"
-		;;
-
-	pull)
-		list="$list_pull"
-		;;
-	push)
-		list="$list_push"
-		;;
-	commit)
-		list="$list_push"
-		;;
-	esac
-
-	_dir_def=$service_dir
-	for _service in $list; do
-		_dir="$_dir_def/$_service"
-
-		case "$_service" in
-		statdeploy)
-			_dir="$_dir_def/stat/etc/conf"
-			;;
-		apideploy)
-			_dir="$_dir_def/api/public/deploy"
-			;;
-		gwmandeploy)
-			_dir="$_dir_def/gwman/data"
-			;;
-		esac
-		_git="git -C $_dir"
-
-		if [ "$cmd" = "commit" ]; then
-			_mydir="$_dir"
-			_git_cmd_commit $_dir $_mydir
-
-		else
-			_git="git -C $_dir"
-			$_git $cmd
-			# commit_id=$($_git rev-parse origin/$($_git rev-parse --abbrev-ref HEAD))
-			# repo_name=$(basename $($_git remote get-url origin) .git)
-			# mkdir -p $SITE_ROOT/public/version
-			# echo $commit_id >$SITE_ROOT/public/version/${repo_name}.version
-		fi
-	done
-
-}
-
-_scan_monitor_type() {
-	dir=$1
-	type=$2
-	format=$3
-	if [ ! -d "$dir/$type" ]; then return 1; fi
-	cd $dir/$type
-
-	find . -type f | sed 's/^\.\///g' | while read f; do
-		id=$(basename $f)
-		group=$type-$(dirname $f | sed 's/\//-/g')
-		name=$group-$id
-		if [ "$type" = "gateway" ]; then
-			group=$(echo $group | cut -d'-' -f1-3)
-			name=$group-$id
-		else
-			group=$type
-		fi
-
-		ip=$(cat $f | jq .ip | sed 's/\"//g')
-
-		if [ "$format" = "address" ]; then
-			echo "\"$name\": \"$ip\","
-		elif [ "$format" = "host" ]; then
-			echo "\"$name\","
-			# echo "\"$name|$group\","
-		elif [ "$format" = "token" ]; then
-			export TOKEN=$(echo -n ${name} | sha1sum | cut -d' ' -f1)
-			echo "$TOKEN $name"
-		fi
-	done
-	return 0
-}
-
-_update_dapi_list() {
-	_type=dapi
-	_dir=$portal_dir/public/deploy/$_type
-	if [ ! -d "$_dir" ]; then return 1; fi
-	info_dir=$portal_dir/public/deploy/info/$_type
-	if [ ! -d "$info_dir" ]; then return; fi
-	mkdir -p $info_dir /tmp/info/$_type
-	rm /tmp/info/$_type/*
-	find $_dir -type f | while read f; do
-		gateway_domain=$(cat $f | jq .gateway_domain | sed 's/\"//g')
-		api_key=$(cat $f | jq .api_key | sed 's/\"//g')
-		block=$(cat $f | jq .blockchain | sed 's/\"//g')
-		net=$(cat $f | jq .network | sed 's/\"//g')
-		user_id=$(cat $f | jq .user_id | sed 's/\"//g')
-		status=$(cat $f | jq .status | sed 's/\"//g')
-		name=$(basename $f)
-		if [ -n "$block" ]; then
-			mesg="$name $user_id $block $net $gateway_domain $api_key $status"
-			echo $mesg >>/tmp/info/$_type/listid
-			echo $mesg >>/tmp/info/$_type/listid-$block-$net
-		fi
-	done
-	rm $info_dir/*
-	mv /tmp/info/$_type/* $info_dir/
-}
-_update_user_list() {
-	_type=user
-	_dir=$portal_dir/public/deploy/$_type
-	if [ ! -d "$info_dir" ]; then return; fi
-	if [ ! -d "$_dir" ]; then return 1; fi
-	info_dir=$portal_dir/public/deploy/info/$_type
-	mkdir -p $info_dir
-	tmp=$(mktemp)
-
-	find $_dir -type f | while read f; do
-		username=$(cat $f | jq .username | sed 's/\"//g')
-		email=$(cat $f | jq .email | sed 's/\"//g')
-		confirmed=$(cat $f | jq .confirmed | sed 's/\"//g')
-		name=$(basename $f)
-		echo "$name $username $email $confirmed" >>$tmp
-
-	done
-	mv $tmp $info_dir/listid
-	chmod 755 $info_dir/listid
-}
-_update_gateway_list() {
-	_type=gateway
-	info_dir=$portal_dir/public/deploy/info/$_type
-	if [ ! -d "$info_dir" ]; then return; fi
-	tmp=$(mktemp)
-	find $info_dir -type f -iname 'listid-*' | while read f; do
-		cat $f >>$tmp
-		echo >>$tmp
-	done
-	mv $tmp $info_dir/listid
-
-}
-_update_node_list() {
-	_type=node
-	info_dir=$portal_dir/public/deploy/info/$_type
-	if [ ! -d "$info_dir" ]; then return; fi
-	tmp=$(mktemp)
-	find $info_dir -type f -iname 'listid-*' | while read f; do
-		cat $f >>$tmp
-		echo >>$tmp
-	done
-	mv $tmp $info_dir/listid
-
-}
 
 _rescan_conf() {
 	svr=$1
@@ -425,31 +203,46 @@ _rescan_conf() {
 	fi
 
 }
-_update_listid() {
-	_update_gateway_list
-	_update_dapi_list
-	_update_node_list
-	mkdir -p $portal_dir/public/deploy/info
-	# _update_user_list
-	if [ -f "$portal_dir/public/deploy/hosts" ]; then
-		cat $portal_dir/public/deploy/hosts >$portal_dir/public/deploy/info/hosts
-		echo >>$portal_dir/public/deploy/info/hosts
-	else
-		>$portal_dir/public/deploy/info/hosts
+
+_install_repos() {
+	if [ -z "$MBR_ENV" ]; then
+		echo "MBR_ENV missing"
+		exit 1
 	fi
-	info_dir=$portal_dir/public/deploy/info/node
-	mkdir -p $info_dir
-	awk -v domain="$DOMAIN" '{print $5,$1".node.mbr."domain}' $info_dir/listid >>$portal_dir/public/deploy/info/hosts
-	info_dir=$portal_dir/public/deploy/info/gateway
-	mkdir -p $info_dir
-	awk -v domain="$DOMAIN" '{print $5,$1".gw.mbr."domain}' $info_dir/listid >>$portal_dir/public/deploy/info/hosts
-}
-_update_repos() {
-	_git_config
 	_repo
-	_update_sources $REPOS
-	_st_repo=$?
-	return $_st_repo
+	_install_sources $REPOS
+	_install_status=$?
+	return $_install_status
+}
+
+_update_repos() {
+	if [ -z "$MBR_ENV" ]; then
+		echo "MBR_ENV missing"
+		exit 1
+	fi
+	if [ -z "$GIT_PRIVATE_READ_URL" ]; then
+		echo "Need GIT_PRIVATE_READ_URL"
+		exit 1
+	fi
+	_repo_private
+	_update_sources $REPOS_PRIVATE
+	_update_status=$?
+	_update_sources $REPOS_RUNTIME
+	return $_update_status
+}
+_commit_repos() {
+	if [ -z "$MBR_ENV" ]; then
+		echo "MBR_ENV missing"
+		exit 1
+	fi
+	if [ -z "$GIT_PRIVATE_READ_URL" ]; then
+		echo "Need GIT_PRIVATE_READ_URL"
+		exit 1
+	fi
+	_repo_private
+	_commit_sources $REPOS_RUNTIME
+	_commit_status=$?
+	return $_commit_status
 }
 
 _cleanupmeforsure() {
@@ -495,62 +288,16 @@ _sync_redis_conf() {
 	done
 }
 _update() {
-	if [ ! -f "$SITE_ROOT/data/geoip/GeoIP2-City.mmdb" ]; then
-		tar -xvJf $SITE_ROOT/data/geoip/GeoIP2-City.mmdb.tar.xz -C $SITE_ROOT/data/geoip
-	fi
-
-	# if [ ! -f "$HOME/.gitconfig" ]; then
-	cat <<EOF >$HOME/.gitconfig
-[http]
-        sslverify = false
-[user]
-	email = baysao@gmail.com
-	name = Baysao
-[safe]
-	directory = /massbit/massbitroute/app/env
-	directory = /massbit/massbitroute/app/gbc
-	directory = /massbit/massbitroute/app/gbc/bin/.asdf
-	directory = /etc/letsencrypt
-	directory = /massbit/massbitroute/app/src/sites/services/api
-	directory = /massbit/massbitroute/app/src/sites/services/api/public/deploy
-	directory = /massbit/massbitroute/app/src/sites/services/node
-	directory = /massbit/massbitroute/app/src/sites/services/gateway
-	directory = /massbit/massbitroute/app/src/sites/services/mkagent
-	directory = /massbit/massbitroute/app/src/sites/services/gwman
-	directory = /massbit/massbitroute/app/src/sites/services/gwman/data
-EOF
-	# fi
-	if [ ! -f "$SITE_ROOT/.env" ]; then
-		cat <<EOF >$SITE_ROOT/.env
-export GIT_PUBLIC_URL="https://github.com"
-export MBR_ENV=$MBR_ENV
-EOF
-	fi
-
 	echo "Update"
+	_prepare
 	_st_update=0
-	# $0 _git_cmd push
 
-	# _update_repos
-	# _st_update=$?
-	#_update_listid
+
+	_update_repos
+	_st_update=$?
+	_commit_repos
 
 	return $_st_update
-}
-
-_reload() {
-	truncate -s 0 $SITE_ROOT/logs/nginx/*
-	truncate -s 0 $SITE_ROOT/logs/*
-	$cmd_server _update
-	# $cmd_server update
-	tmp=$(mktemp)
-	$cmd_server status | grep worker- | awk '{print $1}' >$tmp
-	n=$(cat $tmp | wc -l)
-	cat $tmp | while read f; do
-		echo $cmd_server restart $f
-	done | parallel -j$n
-
-	rm $tmp
 }
 
 _monitor() {
@@ -559,14 +306,12 @@ _monitor() {
 	if [ $is_reload -ne 0 ]; then
 		$0 _reload
 	fi
-	$0 _git_cmd all
-	$0 _git_cmd commit
 
 }
 
 _run() {
 	rm -rf $SITE_ROOT/tmp/*
-
+	_update
 	$SITE_ROOT/start_server
 }
 $@
